import { NextPageWithLayout } from './page';
import Head from 'next/head';
import Image from 'next/image';
import CatCard from '../components/templates/cards/cat/CatCard';
import { mockCatCardProps } from '../components/templates/cards/cat/CatCard.mocks';
import styles from '../styles/Home.module.css';
import PrimaryLayout from '../components/templates/layouts/primary/PrimaryLayout';

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <CatCard
          tag={'Neko Daily'}
          title={'Neko Mon'}
          body={
            'Neko Mon a cutely suspicious animal that can nekofy any individual in contact with it. Neko mon rules with an iron paw. Neko mon survival is still a mystery. Neko mon is a cat. Beware ....'
          }
          author={'Neko Daily Reporter'}
          time={'5:35 PM'}
          {...mockCatCardProps}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

Home.getLayout = (page) => {
  return <PrimaryLayout>{page}</PrimaryLayout>;
};
